### ISSUE TITLE
Lifetime for the cookie seems to be faulty

### ISSUE THREAD

**Issue by sebastianschrama** [urbantrout/site-language-redirection#16]
Or should it really be 50 years and barely 5 months? :)

Actually I wouldn't care, but nowadays you have to use cookie banners and specify the lifetime of the cookie.

**Comment by eyemd** [comment]
Just had the same issue: Right now `time()` is added to `60*60*24*30` in the calculation of `Max/Age` which leads to an expiration date in the 2070s instead of 30 days from today.
Fix would be to just remove `time()+` everywhere in RedirectionMiddleware.php, where the `Max/Age` ist calculated.

**Comment by urbantrout** [comment]
Fixed for todays update.
