### ISSUE TITLE
loss of all get/post data on redirect

### ISSUE THREAD

**Issue by jnkowa-gfk** [urbantrout/site-language-redirection#19]
the **issue**: 
The [current code](https://github.com/urbantrout/site-language-redirection/blob/e6399ad2e4b461993cef7fd078270c229c2a2550/Classes/Middleware/RedirectionMiddleware.php#L189) does the redirect with a status code of `302`.
this in general means that the client will do a redirect by forgetting about the original request but look at the newly given location. usually the request method will be changed from whatever it was to GET and the previously sent data will be forgotten.

The **solution** would be to change the behavior: don't use `302` status code, but use `307` instead. 
benefits of behavior change:
* relocation is still done
* post/get data of original request is sent to the new location

since this is a behavior change, i _suggest_:
* have the http response code used for redirecting to be a setting that defaults to the old behavior `302`
* setting can be overwritten
* have a breaking change in the future, where the default changes from `302` to `307`

**Comment by jnkowa-gfk** [comment]
keep in mind, that for GET a http status code of `307` still might drop data. the query-string needst to be maintained in code.

**Comment by erguenyogurtcu** [comment]
Fixed: https://github.com/urbantrout/site-language-redirection/pull/23

**Comment by achimfritz** [comment]
would be nice to have this PR, works for me

**Comment by Stuffy** [comment]
This was also an issue on our project, we fixed this in a very similar way as the pr of @erguenyogurtcu does. Would be nice to have this integrated into an update, as this extension is the only somewhat up-to-date language redirect solution for typo3.

**Comment by jnkowa-gfk** [comment]
@urbantrout  ping

**Comment by jnkowa-gfk** [comment]
thanks for the merge, @urbantrout .
very much appreciated, looking forward seeing this fix in the next release.

**Comment by urbantrout** [comment]
Thanks for the PR @erguenyogurtcu.  
Will create a new release today.
