### ISSUE TITLE
Android devices causing TYPO3 error in version 2.1.1

### ISSUE THREAD

**Issue by j-lang** [urbantrout/site-language-redirection#6]
After installation of site-language-redirection we noticed two errors:
1. Android devices are getting an error page, the corresponding error message in backend protocol is:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1436717338: Unsupported scheme "android-app"; must be any empty string or in the set (http, https) | InvalidArgumentException thrown in file /html/typo3/typo3_src-9.5.11/typo3/sysext/core/Classes/Http/Uri.php in line 641. `

2. Another error message was fount in TYPO3 protocol but there is no further device/browser information in access.log:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: preg_match() expects parameter 2 to be string, array given | TypeError thrown in file /html/typo3/typo3conf/ext/site_language_redirection/Classes/Middleware/RedirectionMiddleware.php in line 346`  

Extensions is configured for: Browser language (HTTP headers)

**Comment by urbantrout** [comment]
Cannot reproduce. I am using v2.1.1 on a client's site without any problems. Android devices are redirected just fine. 

What exact PHP version are you running?

**Comment by j-lang** [comment]
Lieber Herr Atteneder,

 

habe für sie eine Kopie des Accounts angelegt: https://test.aquawatt.at/home und den Debug-Mode aktiviert damit die Fehlermeldungen ersichtlich sind.

Die fehlenden Daten:

TYPO3 9.5.11

PHP Version 7.2.10

 

Liebe Grüße

 

Hannes Lang

 

 

 

Von: Harald Atteneder [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. November 2019 17:13
An: urbantrout/site-language-redirection <site-language-redirection@noreply.github.com>
Cc: j-lang <johannes.lang@tkc.co.at>; Author <author@noreply.github.com>
Betreff: Re: [urbantrout/site-language-redirection] Android devices causing TYPO3 error in version 2.1.1 (#6)

 

Cannot reproduce. I am using v2.1.1 on a client's site without any problems. Android devices are redirected just fine.

What exact PHP version are you running?

**Comment by urbantrout** [comment]
I don't see any problems:

![Screenshot_20191120-185326](https://user-images.githubusercontent.com/10465787/69264362-76ef1980-0bc7-11ea-8805-6aea88e3f4dd.png)

**Comment by Schweriner** [comment]
I can confirm the same error in the logs - next to 404 error page fetch errors in the log. `$userAgent = array_shift($userAgent);` L:343 does not make sure, that a string is returned if the $userAgent is a multidimensional array. Changing the return to `return is_string($userAgent) && preg_match($this->botPattern, $userAgent);` maybe can solve the problem?

**Comment by urbantrout** [comment]
Thanks @Schweriner for the hint. Could you check if my PR solves the issue?
https://github.com/urbantrout/site-language-redirection/pull/10

**Comment by Schweriner** [comment]
@urbantrout sorry I'm not able to test a redirect based on my browser settings - just had to fix this error. Someone else needs to test if the redirects still work.

**Comment by j-lang** [comment]
Made patch in /Classes/Middleware/RedirectionMiddleware.php but get still error (1) of first post:

![Screenshot_Chrome](https://user-images.githubusercontent.com/7978914/69789482-f0d36400-11c0-11ea-82a8-7b76bbb72c84.jpg)

**Comment by urbantrout** [comment]
what is this android-app scheme? never heard of it.
are you using this in a web app or native app or something?

**Comment by urbantrout** [comment]
Or a PWA?

**Comment by j-lang** [comment]
Samsung Tab S5e or S10+ - Google Chrome, entering URL...

**Comment by urbantrout** [comment]
Could you send me the link to the test installation again. Via email ;)

**Comment by marksh** [comment]
We could reproduce the error with a Google Pixel 3, Android 11
when typing the domain name directly in the Google search field at the mobile's desktop.
The error occurs only if mobile browser(!) language is same as site default languages.

<img width="327" alt="Bildschirmfoto 2020-03-27 um 15 34 04" src="https://user-images.githubusercontent.com/1803632/77767213-022e5f00-7041-11ea-96db-28b58e2e2dd6.png">

**Comment by urbantrout** [comment]
@marksh Thanks for the additional info. I will take a look into it…

**Comment by erguenyogurtcu** [comment]
Any news? The error is still occurring...

**Comment by erguenyogurtcu** [comment]
Fixed: https://github.com/urbantrout/site-language-redirection/pull/20

**Comment by urbantrout** [comment]
Can someone check if this branch solves the problem?

https://github.com/urbantrout/site-language-redirection/tree/android-app-scheme

**Comment by j-lang** [comment]
Great job, now it works! 
Double checked with version 2.1.1 on repo, after updating of your last changes: 
`        // Check if referrer is present and scheme is not `android-app`.
        if ($normalizedParams->getHttpReferer() && substr($normalizedParams->getHttpReferer(), 0, 11) !== 'android-app') {
`
there is no error when loading.
