### ISSUE TITLE
Documentation/howto: Browser language (HTTP headers) fallback 

### ISSUE THREAD

**Issue by j-lang** [urbantrout/site-language-redirection#7]
Can this extension handle language fallback or which configuration task are necessary to handle language fall-backs:
- Default site language is de-DE
- Site configuration has one additional language: hreflang: en-US 

How are hreflang: en-* headers handled? 
How are other languages (IT, FR ... ) routed?  What are necessary configuration task for a proper routing for different site languages and different source languages?

**Comment by urbantrout** [comment]
> How are hreflang: en-* headers handled?

Here is an example on how the extensions detemines the site to redirect to:
If Accept-Language is `en-US,de-AT` it looks for sites with an hreflang of `en-US`. If there is no match it then looks for `en`. If there is still no match it repeats the same logic with `de-AT` and so on.

**Comment by urbantrout** [comment]
Yes, I should add this to the README ;)
